export default {
  'project manager': 'Project Manager',
  'art director': 'Art Director',
  'creative director': 'Creative Director',
  'fullstack': 'Fullstack',
  'frontend': 'Frontend',
  'backend': 'Backend',
  'sysadmin': 'Sysadmin',
  'devops': 'DevOps',
  'designer': 'Designer',
  'senior': 'Senior',
  'junior': 'Junior',
  'html': 'HTML',
  'css': 'CSS',
  'php': 'PHP',
  'javascript': 'JavaScript',
  'python': 'Python',
  'ruby': 'Ruby',
  'c++': 'C++',
  'c#': 'C#',
  'c': 'C',
  'java': 'Java',
  'go': 'Go',
  'swift': 'Swift',
  'sql': 'SQL',
  'seo': 'SEO'
}